### ISSUE TITLE
OOP-1-review-2022-10-15

### ISSUE THREAD

**Issue by hamerlinski** [XoULTRAoX/oop-put-course#1]
**Task 1**
- [ ] Proper communication/interaction between classes and objects is missing
- [x] We should have more classes and their objects
- [x] Rename repository to **oop-put-course**
- [x] Format code properly
- [x] Add file extension

**Task 2**
- [ ] `Iteam`?
- [ ] We should have more constructors
- [x] Add file extension
